### ISSUE TITLE
[FEATURE] META Improvement

### ISSUE THREAD

**Issue by lambda-science** [lambda-science/EHRoes#91]
Backlog of ideas to for META improvement (structure, deployment...):
- [ ] Add Admin Interface to create accounts
- [ ] Remove NGINX Cache or try with production settings (to fix images issues ?)
- [ ] Might add a role-base / user-based gestion of data
